<?php
/**
 * Title: Construction Gallery
 * Slug: gigantic-construction/construction-gallery
 * Categories: gallery
 */
?>

<!-- wp:group {"metadata":{"name":"Construction Gallery"},"align":"full","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"top":"var:preset|spacing|xx-large","bottom":"var:preset|spacing|xx-large","left":"var:preset|spacing|small","right":"var:preset|spacing|small"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--xx-large);padding-right:var(--wp--preset--spacing--small);padding-bottom:var(--wp--preset--spacing--xx-large);padding-left:var(--wp--preset--spacing--small)"><!-- wp:columns {"style":{"spacing":{"margin":{"bottom":"var:preset|spacing|large"},"blockGap":{"top":"0"}}}} -->
<div class="wp-block-columns" style="margin-bottom:var(--wp--preset--spacing--large)"><!-- wp:column {"width":"20%"} -->
<div class="wp-block-column" style="flex-basis:20%"></div>
<!-- /wp:column -->

<!-- wp:column {"width":"60%","style":{"spacing":{"blockGap":"0"}}} -->
<div class="wp-block-column" style="flex-basis:60%"><!-- wp:heading {"textAlign":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"700"}}} -->
<h2 class="wp-block-heading has-text-align-center" style="font-style:normal;font-weight:700"><?php esc_html_e( 'Our Project Excellence', 'gigantic-construction' ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"20%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:20%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"style":{"spacing":{"margin":{"top":"0","bottom":"0"},"blockGap":{"top":"var:preset|spacing|medium","left":"var:preset|spacing|medium"}}}} -->
<div class="wp-block-columns" style="margin-top:0;margin-bottom:0"><!-- wp:column {"verticalAlignment":"bottom"} -->
<div class="wp-block-column is-vertically-aligned-bottom"><!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-01.jpg' ) ); ?>","isUserOverlayColor":true,"minHeight":250,"customGradient":"linear-gradient(0deg,rgba(12,44,97,0.62) 21%,rgba(12,44,97,0) 100%)","contentPosition":"bottom center","sizeSlug":"full","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"radius":"0px"},"spacing":{"padding":{"top":"var:preset|spacing|small","bottom":"var:preset|spacing|small","left":"var:preset|spacing|medium","right":"var:preset|spacing|medium"},"blockGap":"0","margin":{"bottom":"var:preset|spacing|medium"}}},"layout":{"type":"default"}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center" style="border-radius:0px;margin-bottom:var(--wp--preset--spacing--medium);padding-top:var(--wp--preset--spacing--small);padding-right:var(--wp--preset--spacing--medium);padding-bottom:var(--wp--preset--spacing--small);padding-left:var(--wp--preset--spacing--medium);min-height:250px"><img class="wp-block-cover__image-background size-full" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-01.jpg' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgba(12,44,97,0.62) 21%,rgba(12,44,97,0) 100%)"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":4,"style":{"typography":{"fontStyle":"normal","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"var:preset|spacing|x-small"}},"elements":{"link":{"color":{"text":"var:preset|color|accent-text"}}}},"textColor":"accent-text","fontSize":"medium"} -->
<h4 class="wp-block-heading has-accent-text-color has-text-color has-link-color has-medium-font-size" style="margin-top:var(--wp--preset--spacing--x-small);font-style:normal;font-weight:700;line-height:1.2"><?php esc_html_e( 'Urban Nest Project', 'gigantic-construction' ); ?></h4>
<!-- /wp:heading --></div></div>
<!-- /wp:cover -->

<!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-04.jpg' ) ); ?>","isUserOverlayColor":true,"minHeight":450,"customGradient":"linear-gradient(0deg,rgba(12,44,97,0.62) 42%,rgba(255,255,255,0) 100%)","contentPosition":"bottom center","sizeSlug":"full","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"radius":"0px"},"spacing":{"padding":{"top":"var:preset|spacing|small","bottom":"var:preset|spacing|small","left":"var:preset|spacing|small","right":"var:preset|spacing|small"},"blockGap":"0"}},"layout":{"type":"default"}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center" style="border-radius:0px;padding-top:var(--wp--preset--spacing--small);padding-right:var(--wp--preset--spacing--small);padding-bottom:var(--wp--preset--spacing--small);padding-left:var(--wp--preset--spacing--small);min-height:450px"><img class="wp-block-cover__image-background size-full" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-04.jpg' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgba(12,44,97,0.62) 42%,rgba(255,255,255,0) 100%)"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":5,"style":{"typography":{"fontStyle":"normal","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"var:preset|spacing|x-small"}},"elements":{"link":{"color":{"text":"var:preset|color|accent-text"}}}},"textColor":"accent-text"} -->
<h5 class="wp-block-heading has-accent-text-color has-text-color has-link-color" style="margin-top:var(--wp--preset--spacing--x-small);font-style:normal;font-weight:700;line-height:1.2"><?php esc_html_e( 'Solid Foundation', 'gigantic-construction' ); ?></h5>
<!-- /wp:heading --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"bottom"} -->
<div class="wp-block-column is-vertically-aligned-bottom"><!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-02.jpg' ) ); ?>","isUserOverlayColor":true,"minHeight":450,"customGradient":"linear-gradient(0deg,rgba(12,44,97,0.62) 42%,rgba(255,255,255,0) 100%)","contentPosition":"bottom center","sizeSlug":"full","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"radius":"0px"},"spacing":{"padding":{"top":"var:preset|spacing|small","bottom":"var:preset|spacing|small","left":"var:preset|spacing|small","right":"var:preset|spacing|small"},"blockGap":"0","margin":{"bottom":"var:preset|spacing|medium"}}},"layout":{"type":"default"}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center" style="border-radius:0px;margin-bottom:var(--wp--preset--spacing--medium);padding-top:var(--wp--preset--spacing--small);padding-right:var(--wp--preset--spacing--small);padding-bottom:var(--wp--preset--spacing--small);padding-left:var(--wp--preset--spacing--small);min-height:450px"><img class="wp-block-cover__image-background size-full" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-02.jpg' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgba(12,44,97,0.62) 42%,rgba(255,255,255,0) 100%)"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":5,"style":{"typography":{"fontStyle":"normal","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"var:preset|spacing|x-small"}},"elements":{"link":{"color":{"text":"var:preset|color|accent-text"}}}},"textColor":"accent-text"} -->
<h5 class="wp-block-heading has-accent-text-color has-text-color has-link-color" style="margin-top:var(--wp--preset--spacing--x-small);font-style:normal;font-weight:700;line-height:1.2"><?php esc_html_e( 'Unnayan Infrastructure', 'gigantic-construction' ); ?></h5>
<!-- /wp:heading --></div></div>
<!-- /wp:cover -->

<!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-05.jpg' ) ); ?>","isUserOverlayColor":true,"minHeight":250,"customGradient":"linear-gradient(0deg,rgba(12,44,97,0.48) 21%,rgba(12,44,97,0) 100%)","contentPosition":"bottom center","sizeSlug":"full","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"radius":"0px"},"spacing":{"padding":{"top":"var:preset|spacing|small","bottom":"var:preset|spacing|small","left":"var:preset|spacing|medium","right":"var:preset|spacing|medium"},"blockGap":"0","margin":{"bottom":"0"}}},"layout":{"type":"default"}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center" style="border-radius:0px;margin-bottom:0;padding-top:var(--wp--preset--spacing--small);padding-right:var(--wp--preset--spacing--medium);padding-bottom:var(--wp--preset--spacing--small);padding-left:var(--wp--preset--spacing--medium);min-height:250px"><img class="wp-block-cover__image-background size-full" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-05.jpg' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgba(12,44,97,0.48) 21%,rgba(12,44,97,0) 100%)"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":5,"style":{"typography":{"fontStyle":"normal","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"var:preset|spacing|x-small"}},"elements":{"link":{"color":{"text":"var:preset|color|accent-text"}}}},"textColor":"accent-text"} -->
<h5 class="wp-block-heading has-accent-text-color has-text-color has-link-color" style="margin-top:var(--wp--preset--spacing--x-small);font-style:normal;font-weight:700;line-height:1.2"><?php esc_html_e( 'Eco Build Initiative', 'gigantic-construction' ); ?></h5>
<!-- /wp:heading --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"bottom"} -->
<div class="wp-block-column is-vertically-aligned-bottom"><!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-03.jpg' ) ); ?>","isUserOverlayColor":true,"minHeight":250,"customGradient":"linear-gradient(0deg,rgba(12,44,97,0.48) 21%,rgba(12,44,97,0) 100%)","contentPosition":"bottom center","sizeSlug":"full","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"radius":"0px"},"spacing":{"padding":{"top":"var:preset|spacing|small","bottom":"var:preset|spacing|small","left":"var:preset|spacing|medium","right":"var:preset|spacing|medium"},"blockGap":"0","margin":{"bottom":"var:preset|spacing|medium"}}},"layout":{"type":"default"}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center" style="border-radius:0px;margin-bottom:var(--wp--preset--spacing--medium);padding-top:var(--wp--preset--spacing--small);padding-right:var(--wp--preset--spacing--medium);padding-bottom:var(--wp--preset--spacing--small);padding-left:var(--wp--preset--spacing--medium);min-height:250px"><img class="wp-block-cover__image-background size-full" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-03.jpg' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgba(12,44,97,0.48) 21%,rgba(12,44,97,0) 100%)"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":5,"style":{"typography":{"fontStyle":"normal","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"var:preset|spacing|x-small"}},"elements":{"link":{"color":{"text":"var:preset|color|accent-text"}}}},"textColor":"accent-text"} -->
<h5 class="wp-block-heading has-accent-text-color has-text-color has-link-color" style="margin-top:var(--wp--preset--spacing--x-small);font-style:normal;font-weight:700;line-height:1.2"><?php esc_html_e( 'Integrity Build', 'gigantic-construction' ); ?></h5>
<!-- /wp:heading --></div></div>
<!-- /wp:cover -->

<!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-06.jpg' ) ); ?>","isUserOverlayColor":true,"minHeight":450,"customGradient":"linear-gradient(0deg,rgba(12,44,97,0.62) 42%,rgba(255,255,255,0) 100%)","contentPosition":"bottom center","sizeSlug":"full","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"radius":"0px"},"spacing":{"padding":{"top":"var:preset|spacing|small","bottom":"var:preset|spacing|small","left":"var:preset|spacing|small","right":"var:preset|spacing|small"},"blockGap":"0"}},"layout":{"type":"default"}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center" style="border-radius:0px;padding-top:var(--wp--preset--spacing--small);padding-right:var(--wp--preset--spacing--small);padding-bottom:var(--wp--preset--spacing--small);padding-left:var(--wp--preset--spacing--small);min-height:450px"><img class="wp-block-cover__image-background size-full" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/gallery-06.jpg' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgba(12,44,97,0.62) 42%,rgba(255,255,255,0) 100%)"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":5,"style":{"typography":{"fontStyle":"normal","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"var:preset|spacing|x-small"}},"elements":{"link":{"color":{"text":"var:preset|color|accent-text"}}}},"textColor":"accent-text"} -->
<h5 class="wp-block-heading has-accent-text-color has-text-color has-link-color" style="margin-top:var(--wp--preset--spacing--x-small);font-style:normal;font-weight:700;line-height:1.2"><?php esc_html_e( 'Shapla Housing', 'gigantic-construction' ); ?></h5>
<!-- /wp:heading --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->